-- 💡 회원 등급별 할인 쿠폰. 관리자가 등급을 골라 수동으로 발급하고,
-- 결제 시 한 장 선택해 적용한다(사용된 쿠폰은 used_at/order_id가 채워짐).
CREATE TABLE coupons (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL REFERENCES users (id),
    order_id          bigint REFERENCES orders (id),
    name              varchar(100) NOT NULL,
    grade             varchar(20) NOT NULL,
    discount_percent  integer NOT NULL,
    issued_at         timestamptz NOT NULL DEFAULT now(),
    used_at           timestamptz
);

-- 💡 주문 시 쿠폰으로 할인된 금액. total_price는 계속 실제 결제 금액(매출 집계 기준)을 의미한다.
ALTER TABLE orders ADD COLUMN discount_amount integer NOT NULL DEFAULT 0;
