-- 💡 홈 화면 광고 배너. 지금까지 프론트(Home.tsx)에 하드코딩되어 있던 슬라이드를
-- 관리자 페이지에서 편집할 수 있도록 테이블로 옮긴다.
CREATE TABLE banners (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eyebrow      varchar(50) NOT NULL,
    title        varchar(200) NOT NULL,
    description  varchar(300) NOT NULL,
    cta_label    varchar(50) NOT NULL,
    gradient     varchar(200) NOT NULL,
    image_url    varchar(500),
    sort_order   integer NOT NULL DEFAULT 0,
    active       boolean NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- ================= banners: 조회는 모두, 쓰기는 관리자만 (products와 동일 패턴, V11 참고) =================
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;

CREATE POLICY banners_select_all ON banners
    FOR SELECT USING (true);

CREATE POLICY banners_admin_write ON banners
    FOR ALL USING (app_is_admin()) WITH CHECK (app_is_admin());
