-- 💡 카테고리 관리 화면에서 쓰기(등록/수정/삭제)가 생기므로, products/banners와 동일하게
-- categories에도 RLS를 켠다(V11 당시엔 조회 전용이라 빠져 있었다).
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY categories_select_all ON categories
    FOR SELECT USING (true);

CREATE POLICY categories_admin_write ON categories
    FOR ALL USING (app_is_admin()) WITH CHECK (app_is_admin());

-- 💡 상품 뱃지(NEW/SALE/BEST 등)의 이름과 표시 색상을 관리자가 등록/수정할 수 있게 하는 테이블.
-- Product.badge는 여전히 자유 문자열이라(BadgeService가 이름 변경/삭제 시 상품을 같이 정리),
-- 기존 3종 뱃지를 ProductCard.module.css에 있던 그라디언트 색상 그대로 시드한다.
CREATE TABLE badges (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(30) NOT NULL UNIQUE,
    color_from  varchar(20) NOT NULL,
    color_to    varchar(20) NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE badges ENABLE ROW LEVEL SECURITY;

CREATE POLICY badges_select_all ON badges
    FOR SELECT USING (true);

CREATE POLICY badges_admin_write ON badges
    FOR ALL USING (app_is_admin()) WITH CHECK (app_is_admin());

INSERT INTO badges (name, color_from, color_to) VALUES
    ('NEW', '#2563eb', '#38bdf8'),
    ('SALE', '#dc2626', '#f97316'),
    ('BEST', '#16a34a', '#86efac');
