-- 💡 Flyway 도입 시점의 실제 운영 DB(Supabase) 스키마를 그대로 옮겨 적은 베이스라인.
-- 기존 DB에는 baselineOnMigrate로 "이미 적용됨" 표시만 하고 실행하지 않으며,
-- 새로 DB를 준비하는 개발자 환경에서는 이 파일이 실제로 실행되어 스키마를 만든다.
-- 이후 스키마 변경은 ddl-auto가 아니라 V2, V3 ... 마이그레이션 파일로 추가한다.

CREATE TABLE categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE teams (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE users (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             varchar(255),
    name              varchar(255),
    password          varchar(255),
    role              varchar(255),
    favorite_team_id  bigint REFERENCES teams (id)
);

CREATE TABLE products (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(255),
    category_id    bigint NOT NULL REFERENCES categories (id),
    team_id        bigint REFERENCES teams (id),
    price          integer,
    original_price integer,
    rating         double precision NOT NULL,
    review_count   integer NOT NULL,
    emoji          varchar(255),
    badge          varchar(255),
    use_at         varchar(255),
    stock          integer NOT NULL DEFAULT 50,
    status         varchar(10) NOT NULL DEFAULT '판매중',
    created_at     timestamp NOT NULL DEFAULT now(),
    sold_count     integer NOT NULL DEFAULT 0
);

CREATE TABLE cart_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL REFERENCES users (id),
    product_id bigint NOT NULL REFERENCES products (id),
    quantity   integer NOT NULL,
    UNIQUE (user_id, product_id)
);

CREATE TABLE wishlist_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL REFERENCES users (id),
    product_id bigint NOT NULL REFERENCES products (id),
    UNIQUE (user_id, product_id)
);

CREATE TABLE orders (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL REFERENCES users (id),
    total_price       integer,
    status            varchar(255),
    created_at        timestamptz,
    shipping_address  varchar(255),
    tracking_number   varchar(255)
);

CREATE TABLE order_items (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     bigint NOT NULL REFERENCES orders (id),
    product_name varchar(255),
    category     varchar(255),
    emoji        varchar(255),
    unit_price   integer,
    quantity     integer NOT NULL,
    -- 💡 현재 엔티티(OrderItem.java)에는 대응하는 필드가 없는 미사용 컬럼.
    -- ddl-auto=update는 컬럼을 자동으로 지우지 않아 과거 설계의 흔적이 남아있는 상태 그대로 베이스라인에 포함한다.
    item_index   integer
);
