-- 💡 상품 리뷰. 한 회원이 같은 상품에 리뷰를 여러 개 남길 수 없도록 (product_id, user_id) 유니크 제약을 둔다.
CREATE TABLE reviews (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products (id),
    user_id    bigint NOT NULL REFERENCES users (id),
    rating     integer NOT NULL,
    content    varchar(1000) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reviews_product_id_user_id_key UNIQUE (product_id, user_id)
);
